### Садыков Ильдар 09-812, дз на 14.10.2020

#### Вариант 4

In [1]:
from random import randint
import itertools
from functools import reduce
import numpy as np

In [2]:
n, m = 5, 5

In [3]:
matrix = [[randint(-9, 9) for j in range(m)] for i in range(n)]

In [4]:
matrix

[[0, -3, 3, -8, 5],
 [-4, 1, -1, 3, 8],
 [-7, -1, 5, 3, -4],
 [-4, -4, 6, 2, -9],
 [7, 0, -7, 0, -8]]

1. Найти сумму, произведение, минимальный и максимальный элемент заданной матрицы среди
элементов, меньших 1 и расположенных в нечетных строках

In [5]:
sample = [matrix[i][j] for (i, j) in itertools.product(range(n), range(m)) if matrix[i][j] < 1 and i % 2 != 0]

In [6]:
sample

[-4, -1, -4, -4, -9]

In [7]:
sum(sample)

-22

In [8]:
reduce(lambda x, y: x * y, sample)

-576

In [9]:
min(sample)

-9

In [10]:
max(sample)

-1

2. Найти сумму, произведение, минимальный и максимальный элемент заданной матрицы среди
элементов, расположенных выше главной диагонали
a. без использования встроенных функций;
b. используя встроенные функции Python (функции работы со списками, срезы, библиотека Numpy)

a)

In [11]:
summa, mul, minim, maxim = 0, 1, matrix[0][0], matrix[0][0]

In [12]:
for i in range(n):
    for j in range(i + 1, m):
        summa += matrix[i][j]
        mul *= matrix[i][j]
        minim = matrix[i][j] if matrix[i][j] < minim else minim
        maxim = matrix[i][j] if matrix[i][j] > maxim else maxim

In [13]:
summa

-3

In [14]:
mul

-933120

In [15]:
minim

-9

In [16]:
maxim

8

b)

In [17]:
np_matrix = np.array(matrix)

In [18]:
np_matrix

array([[ 0, -3,  3, -8,  5],
       [-4,  1, -1,  3,  8],
       [-7, -1,  5,  3, -4],
       [-4, -4,  6,  2, -9],
       [ 7,  0, -7,  0, -8]])

In [19]:
above_diagonal = np.array([np_matrix[i][j] for (i, j) in itertools.product(range(n), range(m)) if j > i])

In [20]:
above_diagonal

array([-3,  3, -8,  5, -1,  3,  8,  3, -4, -9])

3. Найти произведение элементов столбца, в котором расположен наибольший элемент заданной матрицы.

In [34]:
index = max([(i, max(row)) for i, row in enumerate(matrix)], key=lambda x: x[1])[0]

In [35]:
reduce(lambda a, b: a * b, matrix[index])

96

4. Построить одномерный массив, состоящий из наименьших элементов каждого столбца
a. без использования встроенных функций;
b. используя встроенные функции Python (функции работы со списками, срезы, библиотека Numpy)

a)

In [36]:
array = []

In [37]:
for i in range(n):
    minimum = matrix[0][i]
    for j in range(m):
        if matrix[j][i] < minimum:
            minimum = matrix[j][i]
    array.append(minimum)

In [38]:
array

[-7, -4, -7, -8, -9]

b)

In [41]:
array = np.array([min(arr) for arr in np_matrix.transpose()])

In [42]:
array

array([-7, -4, -7, -8, -9])